name: Neofetch and Disk Space
on: push
jobs:
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: Install neofetch
        run:
              sudo apt install neofetch
              df -h
      - name: Run neofetch
        run: neofetch
      
